In [1]:
import requests
import numpy as np
import pandas as pd
%run ../employee/links.ipynb

In [2]:
req = requests.get(links_ns.position.all_active).json()
position = pd.json_normalize(req)

In [4]:
select_col = ["positionId","employee.employeeId",
              "subdivision.code",'service.subdivision.code']
rename_col = ["positionId","employeeId",
              "codeA","codeB"]
position_df = position[select_col].copy()
position_df.columns = rename_col
position_df["direction"] = position_df.codeA.fillna(position_df.codeB)
position_df.drop(columns=["codeA","codeB"], inplace=True)
position_df.direction = position_df.direction.map(lambda x: x.split("_")[1])

In [14]:
df = position_df.copy()
employee_ids_by_direction = {}
# Loop through each unique direction in the DataFrame
for direction in df['direction'].unique():
    direction_df = df[df['direction'] == direction]
    employee_ids = direction_df['employeeId'].tolist()
    employee_ids_by_direction[direction] = employee_ids
#print(employee_ids_by_direction)

In [17]:
def filter_df_by_col_value(df, col, value, matcher = employee_ids_by_direction):
    # Filter the DataFrame to only include rows with the "DRRN" direction
    drn_df = df[df[col] == value]
    # Get the employee IDs for the "DRRN" direction from the dictionary
    employee_ids = matcher[value]
    # Filter the "DRRN" DataFrame to only include rows with employee IDs in the list
    return drn_df[drn_df['positionId'].isin(employee_ids)]

In [18]:
filter_df_by_col_value(position_df, "direction", "DSE")

   positionId  employeeId direction
5           6           6       DSE
9          10          10       DSE

In [11]:
position_df

    positionId  employeeId direction
0            1           1       DSI
1            2           2       DCP
2            3           3      DRRN
3            4           4     DCSTI
4            5           5       DSP
5            6           6       DSE
6            7           7      DMGP
7            8           8      DMGP
8            9           9     DCSTI
9           10          10       DSE
10          11          11      DMGP
11          12          12   DGPECRP
12          13          13      DMGP
13          14          14      DRRN
14          15          15      DMGP
15          16          16      DMGP
16          17          17      DMGP
17          18          18      DRRN
18          19          19      DRRN
19          20          20      DMGP
20          21          21        PR
21          22          22      DMGP
22          23          23        DG
23          24          24     DSESP
24          25          25      DMGP
25          26          26       DCP
26          27          27      DMGP
27          28          28   DGPECRP
28          29           6       DSE